import { randomUUID } from "node:crypto";
import { existsSync, mkdirSync, readdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

const MAX_FILE_CHARS = 40_000;
const SAFE_TASK_ID_RE = /^[a-zA-Z0-9._-]+$/;

export const CHECKPOINT_TEMPLATE = `# Session checkpoint
_Generated by checkpoint writer; structure preserved across updates. Edit only content under italic instructions._

## §1 Active intent
_User's most recent explicit request, verbatim when possible. The request is the ground truth; do not paraphrase away constraints._
(none yet)

## §2 Next concrete action
_The single next concrete step, derived from §1 and current state. Name the file, function, or exact command when known._
(none yet)

## §3 Directives (this session)
_Session-specific working style only. Project-level rules belong in MEMORY.md; do not duplicate them here._
(none)

## §4 Task tree
_Hierarchical task state with the current focus marked. Link delegated work to tasks/<id>/progress.md._
(none yet)

## §5 Current work
_What was being done immediately before this checkpoint, including concrete files and code locations._
(none yet)

## §6 Files and code sections
_Files actively read or modified, with a one-line purpose._
(none yet)

## §7 Discovered knowledge (cross-task)
_Facts learned in this session that may survive the task. Promote only durable facts to MEMORY.md._
(none yet)

## §8 Errors and fixes
_Errors encountered and how they were resolved, newest first._
(none)

## §9 Live resources
_Runtime state: branch, processes, temporary files, and other volatile state. Keep it concise._
(none yet)

## §10 Design decisions and discussion outcomes
_Decisions reached in discussion that explain why the implementation looks this way._
(none yet)

## §11 Open notes
_Unresolved questions, quotes, and observations that do not fit §1–§10._
(none yet)
`;

export const MEMORY_TEMPLATE = `# Project memory

_Durable project-level knowledge. This file is shared by all sessions._

## Project context
(none yet)

## Rules
(none yet)

## Architecture decisions
(none yet)

## Discovered durable knowledge
(none yet)
`;

export const NOTES_TEMPLATE = `# Session notes

_Free-form scratchpad. The checkpoint writer reconciles entries at checkpoints._
`;

export function memoryRoot(): string {
	return process.env.CAST_MEMORY_DIR || join(homedir(), ".cast", "memory");
}

/** Claude Code memory root; CAST_CC_MEMORY_DIR lets tests isolate the walk. */
export function ccMemoryRoot(): string {
	return process.env.CAST_CC_MEMORY_DIR || join(homedir(), ".claude", "projects");
}

export function sessionMemoryDir(sessionId: string): string {
	return join(memoryRoot(), "sessions", sessionId);
}

export function checkpointPath(sessionId: string): string {
	return join(sessionMemoryDir(sessionId), "checkpoint.md");
}

export function notesPath(sessionId: string): string {
	return join(sessionMemoryDir(sessionId), "notes.md");
}

export function tasksDir(sessionId: string): string {
	return join(sessionMemoryDir(sessionId), "tasks");
}

export function taskProgressPath(sessionId: string, taskId: string): string {
	if (!SAFE_TASK_ID_RE.test(taskId)) throw new Error("Invalid task id");
	return join(tasksDir(sessionId), taskId, "progress.md");
}

export function projectMemoryPath(projectId: string): string {
	return join(memoryRoot(), "projects", projectId, "MEMORY.md");
}

export function projectMemoryManifestPath(projectId: string): string {
	return join(memoryRoot(), "projects", projectId, "manifest.json");
}

export function globalMemoryPath(): string {
	return join(memoryRoot(), "global", "MEMORY.md");
}

export interface ProjectMemoryManifest {
	version: 1;
	revision: number;
	projectId: string;
	sessionId: string;
	projectHash: string;
	checkpointHash: string;
	updatedAt: string;
}

export function writeProjectMemoryManifest(projectId: string, manifest: ProjectMemoryManifest): void {
	writeMemoryFile(projectMemoryManifestPath(projectId), `${JSON.stringify(manifest, null, 2)}\n`);
}

export function ensureMemoryFiles(sessionId: string, projectId: string): void {
	const files: Array<[string, string]> = [
		[checkpointPath(sessionId), CHECKPOINT_TEMPLATE],
		[notesPath(sessionId), NOTES_TEMPLATE],
		[projectMemoryPath(projectId), MEMORY_TEMPLATE],
	];
	for (const [path, template] of files) {
		mkdirSync(dirname(path), { recursive: true });
		if (!existsSync(path)) writeFileSync(path, template, "utf8");
	}
	mkdirSync(tasksDir(sessionId), { recursive: true });
}

export function readMemoryFile(path: string, fallback = ""): string {
	try {
		return readFileSync(path, "utf8").slice(0, MAX_FILE_CHARS);
	} catch {
		return fallback;
	}
}

export interface CheckedMemoryFile {
	readable: boolean;
	content: string;
}

/** Distinguishes an intentionally empty file from an I/O failure. */
export function readMemoryFileChecked(path: string): CheckedMemoryFile {
	try {
		return { readable: true, content: readFileSync(path, "utf8").slice(0, MAX_FILE_CHARS) };
	} catch {
		return { readable: false, content: "" };
	}
}

export function readSessionMemory(sessionId: string): { checkpoint: string; notes: string; taskProgress: string } {
	const progress: string[] = [];
	try {
		for (const entry of readdirSync(tasksDir(sessionId), { withFileTypes: true })) {
			if (!entry.isDirectory()) continue;
			const content = readMemoryFile(taskProgressPath(sessionId, entry.name));
			if (content) progress.push(`### ${entry.name}\n${content}`);
		}
	} catch {
		// The session may not have delegated any tasks yet.
	}
	return {
		checkpoint: readMemoryFile(checkpointPath(sessionId)),
		notes: readMemoryFile(notesPath(sessionId)),
		taskProgress: progress.join("\n\n").slice(0, MAX_FILE_CHARS),
	};
}

export function readProjectMemory(projectId: string): string {
	return readMemoryFile(projectMemoryPath(projectId));
}

export function writeMemoryFile(path: string, content: string): void {
	mkdirSync(dirname(path), { recursive: true });
	const tempPath = `${path}.${process.pid}.${randomUUID()}.tmp`;
	writeFileSync(tempPath, content, "utf8");
	renameSync(tempPath, path);
}

export function appendSessionNote(sessionId: string, content: string): void {
	const path = notesPath(sessionId);
	const previous = readMemoryFile(path, NOTES_TEMPLATE).trimEnd();
	const next = `${previous}\n\n## [${new Date().toISOString()}]\n${content.trim()}\n`;
	writeMemoryFile(path, next);
}

export function writeTaskProgress(sessionId: string, taskId: string, content: string): void {
	writeMemoryFile(taskProgressPath(sessionId, taskId), `${content.trimEnd()}\n`);
}

export function renderCheckpoint(checkpoint: {
	activeIntent: string;
	nextAction: string;
	directives: string[];
	taskTree: string[];
	currentWork: string[];
	files: string[];
	discoveredKnowledge: string[];
	errorsFixes: string[];
	liveResources: string[];
	designDecisions: string[];
	openNotes: string[];
}): string {
	const sections: Array<[string, string]> = [
		["§1 Active intent", checkpoint.activeIntent || "(none yet)"],
		["§2 Next concrete action", checkpoint.nextAction || "(none yet)"],
		["§3 Directives (this session)", checkpoint.directives.join("\n") || "(none)"],
		["§4 Task tree", checkpoint.taskTree.join("\n") || "(none yet)"],
		["§5 Current work", checkpoint.currentWork.join("\n") || "(none yet)"],
		["§6 Files and code sections", checkpoint.files.join("\n") || "(none yet)"],
		["§7 Discovered knowledge (cross-task)", checkpoint.discoveredKnowledge.join("\n") || "(none yet)"],
		["§8 Errors and fixes", checkpoint.errorsFixes.join("\n") || "(none)"],
		["§9 Live resources", checkpoint.liveResources.join("\n") || "(none yet)"],
		["§10 Design decisions and discussion outcomes", checkpoint.designDecisions.join("\n") || "(none yet)"],
		["§11 Open notes", checkpoint.openNotes.join("\n") || "(none yet)"],
	];
	return `# Session checkpoint\n_Generated by checkpoint writer; structure preserved across updates.\n\n${sections.map(([title, body]) => `## ${title}\n${body}`).join("\n\n")}\n`;
}
